Traceback (most recent call last):
  File "run.py", line 218, in <module>
    train_loop(save_path)
  File "run.py", line 71, in train_loop
    model = RNN_two_layers(input_size, hs, output_size, feedback_scaling, loss_func, nonlin)
TypeError: __init__() takes 6 positional arguments but 7 were given
Traceback (most recent call last):
  File "run.py", line 218, in <module>
    train_loop(save_path)
  File "run.py", line 71, in train_loop
    model = RNN_two_layers(input_size, hs, output_size, feedback_scaling, loss_func, nonlin)
TypeError: __init__() takes 6 positional arguments but 7 were given